gems:
  - jemoji
  - jekyll-paginate

title: "Alfie.cat"
description: > # this means to ignore newlines until "email:"
  October 1986, Tacita de plata. I was born naked, wet and hungry. After that, I became a software engineer. I make stuff. My favourite shapes are spades, hearts, diamonds, clubs and hamburgers.

email: me@alfie.cat

name: 'Alfonso Jiménez'
author: 'Alfonso Jiménez'
author_image: "https://alfie.cat/assets/images/author.jpg"
author_bio: "Software Engineer at Jobandtalent"

paginate:	8

url: "https://alfie.cat"
enforce_ssl: alfie.cat
baseurl: ""
#used to display twitter cards
twitter_handle: '@alfonsojimenez'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/alfonsojimenez
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	linkedin
    url:	https://linkedin.com/in/alfonsojimenez
    desc:	LinkedIn
    share_url:
    share_title:
    share_link:

  - icon:	angellist
    url:	https://angel.co/alfonsojimenez
    desc:	Angellist
    share_url:
    share_title:
    share_link:

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/alfonsojimenez
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	instagram
    url:	https://instagram.com/alfonsojimenez
    desc:	Follow me on instagram
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:

theme: jekyll-theme-cayman